theme: jekyll-theme-cayman
title: Frosty - the cake decorator!
description: Welcome to our Final Project for ESE350! Here we will demonstrate how we made a cake decorator using embedded systems. Made by: Alice Bian, Rohan Saraogi, Derya Yavuz
